version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      npm-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 3

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      python-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      workflow-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 3
